import requests
import json

apikey = "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdSI6Imx4ZzphcGkiLCJzYyI6WyJrZzpyZWFkIiwiZXh0cmFjdGlvbjpyZWFkIl0sImFpIjoiYXBpOjdiZjYzMzA3LWNjOTMtYjFiNS1mYjVhLWY1NzY4MzIwNjlkNyIsInVpIjoidXNlcjozNGU1MWQ2MC0wY2MxLTk2NGUtMjM2Yi0yZTI2OTdlMzMxYmQiLCJpYXQiOjE1NDk3NDU0MDJ9.GE0eQXmt7aMiYcxSfA26LhZhzQHsXQ7qFkOCv7LtSRA"
